openapi: 3.0.3
info:
  title: User Service
  description: Service for getting user info
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /openapi.json:
    get:
      tags:
      - user
      summary: Download ./gen/http/openapi.json
      operationId: user#/openapi.json
      responses:
        "200":
          description: File downloaded
  /user:
    get:
      tags:
      - user
      summary: get user
      description: Returns User details
      operationId: user#get
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponseBody'
              example:
                companies:
                - id: 15652828213867574851
                  location: Et deleniti voluptates deserunt.
                  name: Saepe blanditiis vitae quasi.
                - id: 15652828213867574851
                  location: Et deleniti voluptates deserunt.
                  name: Saepe blanditiis vitae quasi.
                - id: 15652828213867574851
                  location: Et deleniti voluptates deserunt.
                  name: Saepe blanditiis vitae quasi.
                - id: 15652828213867574851
                  location: Et deleniti voluptates deserunt.
                  name: Saepe blanditiis vitae quasi.
                id: 9906874151693549962
                latestCompany:
                  name: Praesentium officia quas eos consectetur.
                name: Assumenda architecto cum et quod.
  /user2:
    get:
      tags:
      - user
      summary: get2 user
      description: Returns User details
      operationId: user#get2
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Get2ResponseBodyV1'
              example:
                id: 12778347463735241895
                name: Esse debitis.
components:
  schemas:
    Get2ResponseBodyV1:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the user
          example: 2762580632545096489
        name:
          type: string
          description: Name of user
          example: Eos perspiciatis repellendus ut et aut voluptas.
      description: Get2ResponseBody result type (v1 view)
      example:
        id: 11330408712948978623
        name: Neque est quisquam.
      required:
      - id
      - name
    GetResponseBody:
      type: object
      properties:
        companies:
          type: array
          items:
            $ref: '#/components/schemas/UserCompany2'
          description: all companies user worked at
          example:
          - id: 15652828213867574851
            location: Et deleniti voluptates deserunt.
            name: Saepe blanditiis vitae quasi.
          - id: 15652828213867574851
            location: Et deleniti voluptates deserunt.
            name: Saepe blanditiis vitae quasi.
          - id: 15652828213867574851
            location: Et deleniti voluptates deserunt.
            name: Saepe blanditiis vitae quasi.
          - id: 15652828213867574851
            location: Et deleniti voluptates deserunt.
            name: Saepe blanditiis vitae quasi.
        id:
          type: integer
          description: ID is the unique id of the user
          example: 11652591273445952281
        latestCompany:
          $ref: '#/components/schemas/UserCompany'
        name:
          type: string
          description: Name of user
          example: Dolores odit odit aperiam.
      description: GetResponseBody result type (default view)
      example:
        companies:
        - id: 15652828213867574851
          location: Et deleniti voluptates deserunt.
          name: Saepe blanditiis vitae quasi.
        - id: 15652828213867574851
          location: Et deleniti voluptates deserunt.
          name: Saepe blanditiis vitae quasi.
        - id: 15652828213867574851
          location: Et deleniti voluptates deserunt.
          name: Saepe blanditiis vitae quasi.
        - id: 15652828213867574851
          location: Et deleniti voluptates deserunt.
          name: Saepe blanditiis vitae quasi.
        id: 15286478875011481673
        latestCompany:
          name: Praesentium officia quas eos consectetur.
        name: Consequatur ipsam quis.
      required:
      - id
      - name
      - latestCompany
      - companies
    UserCompany:
      type: object
      properties:
        name:
          type: string
          description: Name of company
          example: Temporibus illum ut cupiditate voluptatibus.
      example:
        name: Quo enim esse laboriosam perferendis non.
      required:
      - id
      - name
      - location
    UserCompany2:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the company
          example: 16018091000447204358
        location:
          type: string
          description: Location of company
          example: Nobis voluptas quos sint.
        name:
          type: string
          description: Name of company
          example: Voluptatem ipsam ipsam voluptatum temporibus sit.
      example:
        id: 2146091552247203196
        location: Repudiandae est suscipit non.
        name: Qui voluptatem inventore molestiae ratione similique.
      required:
      - id
      - name
      - location
